/*
 * Trello
 * This document describes the REST API of Trello as published by Trello.com.  - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>  - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Boards
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-05-12T10:27:01.792+02:00[Europe/Berlin]")
public class Boards {
  @SerializedName("closed")
  private String closed = null;

  @SerializedName("desc")
  private String desc = null;

  @SerializedName("idBoardSource")
  private String idBoardSource = null;

  @SerializedName("idOrganization")
  private String idOrganization = null;

  @SerializedName("keepFromSource")
  private String keepFromSource = null;

  @SerializedName("labelNames/blue")
  private String labelNamesblue = null;

  @SerializedName("labelNames/green")
  private String labelNamesgreen = null;

  @SerializedName("labelNames/orange")
  private String labelNamesorange = null;

  @SerializedName("labelNames/purple")
  private String labelNamespurple = null;

  @SerializedName("labelNames/red")
  private String labelNamesred = null;

  @SerializedName("labelNames/yellow")
  private String labelNamesyellow = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("powerUps")
  private String powerUps = null;

  @SerializedName("prefs/background")
  private String prefsbackground = null;

  @SerializedName("prefs/calendarFeedEnabled")
  private String prefscalendarFeedEnabled = null;

  @SerializedName("prefs/cardAging")
  private String prefscardAging = null;

  @SerializedName("prefs/cardCovers")
  private String prefscardCovers = null;

  @SerializedName("prefs/comments")
  private String prefscomments = null;

  @SerializedName("prefs/invitations")
  private String prefsinvitations = null;

  @SerializedName("prefs/permissionLevel")
  private String prefspermissionLevel = null;

  @SerializedName("prefs/selfJoin")
  private String prefsselfJoin = null;

  @SerializedName("prefs/voting")
  private String prefsvoting = null;

  @SerializedName("prefs_background")
  private String prefsBackground = null;

  @SerializedName("prefs_cardAging")
  private String prefsCardAging = null;

  @SerializedName("prefs_cardCovers")
  private String prefsCardCovers = null;

  @SerializedName("prefs_comments")
  private String prefsComments = null;

  @SerializedName("prefs_invitations")
  private String prefsInvitations = null;

  @SerializedName("prefs_permissionLevel")
  private String prefsPermissionLevel = null;

  @SerializedName("prefs_selfJoin")
  private String prefsSelfJoin = null;

  @SerializedName("prefs_voting")
  private String prefsVoting = null;

  @SerializedName("subscribed")
  private String subscribed = null;

  public Boards closed(String closed) {
    this.closed = closed;
    return this;
  }

   /**
   *  true or false
   * @return closed
  **/
  @Schema(description = " true or false")
  public String getClosed() {
    return closed;
  }

  public void setClosed(String closed) {
    this.closed = closed;
  }

  public Boards desc(String desc) {
    this.desc = desc;
    return this;
  }

   /**
   * a string with a length from 0 to 16384
   * @return desc
  **/
  @Schema(description = "a string with a length from 0 to 16384")
  public String getDesc() {
    return desc;
  }

  public void setDesc(String desc) {
    this.desc = desc;
  }

  public Boards idBoardSource(String idBoardSource) {
    this.idBoardSource = idBoardSource;
    return this;
  }

   /**
   * The id of the board to copy into the new board
   * @return idBoardSource
  **/
  @Schema(description = "The id of the board to copy into the new board")
  public String getIdBoardSource() {
    return idBoardSource;
  }

  public void setIdBoardSource(String idBoardSource) {
    this.idBoardSource = idBoardSource;
  }

  public Boards idOrganization(String idOrganization) {
    this.idOrganization = idOrganization;
    return this;
  }

   /**
   * The id or name of the organization to add the board to.
   * @return idOrganization
  **/
  @Schema(description = "The id or name of the organization to add the board to.")
  public String getIdOrganization() {
    return idOrganization;
  }

  public void setIdOrganization(String idOrganization) {
    this.idOrganization = idOrganization;
  }

  public Boards keepFromSource(String keepFromSource) {
    this.keepFromSource = keepFromSource;
    return this;
  }

   /**
   * Components of the source board to copy.
   * @return keepFromSource
  **/
  @Schema(description = "Components of the source board to copy.")
  public String getKeepFromSource() {
    return keepFromSource;
  }

  public void setKeepFromSource(String keepFromSource) {
    this.keepFromSource = keepFromSource;
  }

  public Boards labelNamesblue(String labelNamesblue) {
    this.labelNamesblue = labelNamesblue;
    return this;
  }

   /**
   * a string with a length from 0 to 16384
   * @return labelNamesblue
  **/
  @Schema(description = "a string with a length from 0 to 16384")
  public String getLabelNamesblue() {
    return labelNamesblue;
  }

  public void setLabelNamesblue(String labelNamesblue) {
    this.labelNamesblue = labelNamesblue;
  }

  public Boards labelNamesgreen(String labelNamesgreen) {
    this.labelNamesgreen = labelNamesgreen;
    return this;
  }

   /**
   * a string with a length from 0 to 16384
   * @return labelNamesgreen
  **/
  @Schema(description = "a string with a length from 0 to 16384")
  public String getLabelNamesgreen() {
    return labelNamesgreen;
  }

  public void setLabelNamesgreen(String labelNamesgreen) {
    this.labelNamesgreen = labelNamesgreen;
  }

  public Boards labelNamesorange(String labelNamesorange) {
    this.labelNamesorange = labelNamesorange;
    return this;
  }

   /**
   * a string with a length from 0 to 16384
   * @return labelNamesorange
  **/
  @Schema(description = "a string with a length from 0 to 16384")
  public String getLabelNamesorange() {
    return labelNamesorange;
  }

  public void setLabelNamesorange(String labelNamesorange) {
    this.labelNamesorange = labelNamesorange;
  }

  public Boards labelNamespurple(String labelNamespurple) {
    this.labelNamespurple = labelNamespurple;
    return this;
  }

   /**
   * a string with a length from 0 to 16384
   * @return labelNamespurple
  **/
  @Schema(description = "a string with a length from 0 to 16384")
  public String getLabelNamespurple() {
    return labelNamespurple;
  }

  public void setLabelNamespurple(String labelNamespurple) {
    this.labelNamespurple = labelNamespurple;
  }

  public Boards labelNamesred(String labelNamesred) {
    this.labelNamesred = labelNamesred;
    return this;
  }

   /**
   * a string with a length from 0 to 16384
   * @return labelNamesred
  **/
  @Schema(description = "a string with a length from 0 to 16384")
  public String getLabelNamesred() {
    return labelNamesred;
  }

  public void setLabelNamesred(String labelNamesred) {
    this.labelNamesred = labelNamesred;
  }

  public Boards labelNamesyellow(String labelNamesyellow) {
    this.labelNamesyellow = labelNamesyellow;
    return this;
  }

   /**
   * a string with a length from 0 to 16384
   * @return labelNamesyellow
  **/
  @Schema(description = "a string with a length from 0 to 16384")
  public String getLabelNamesyellow() {
    return labelNamesyellow;
  }

  public void setLabelNamesyellow(String labelNamesyellow) {
    this.labelNamesyellow = labelNamesyellow;
  }

  public Boards name(String name) {
    this.name = name;
    return this;
  }

   /**
   * a string with a length from 1 to 16384
   * @return name
  **/
  @Schema(description = "a string with a length from 1 to 16384")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Boards powerUps(String powerUps) {
    this.powerUps = powerUps;
    return this;
  }

   /**
   * all or a comma-separated list of: calendar, cardAging, recap or voting
   * @return powerUps
  **/
  @Schema(description = "all or a comma-separated list of: calendar, cardAging, recap or voting")
  public String getPowerUps() {
    return powerUps;
  }

  public void setPowerUps(String powerUps) {
    this.powerUps = powerUps;
  }

  public Boards prefsbackground(String prefsbackground) {
    this.prefsbackground = prefsbackground;
    return this;
  }

   /**
   * A standard background name, or the id of a custom background
   * @return prefsbackground
  **/
  @Schema(description = "A standard background name, or the id of a custom background")
  public String getPrefsbackground() {
    return prefsbackground;
  }

  public void setPrefsbackground(String prefsbackground) {
    this.prefsbackground = prefsbackground;
  }

  public Boards prefscalendarFeedEnabled(String prefscalendarFeedEnabled) {
    this.prefscalendarFeedEnabled = prefscalendarFeedEnabled;
    return this;
  }

   /**
   *  true or false
   * @return prefscalendarFeedEnabled
  **/
  @Schema(description = " true or false")
  public String getPrefscalendarFeedEnabled() {
    return prefscalendarFeedEnabled;
  }

  public void setPrefscalendarFeedEnabled(String prefscalendarFeedEnabled) {
    this.prefscalendarFeedEnabled = prefscalendarFeedEnabled;
  }

  public Boards prefscardAging(String prefscardAging) {
    this.prefscardAging = prefscardAging;
    return this;
  }

   /**
   * One of: pirate or regular
   * @return prefscardAging
  **/
  @Schema(description = "One of: pirate or regular")
  public String getPrefscardAging() {
    return prefscardAging;
  }

  public void setPrefscardAging(String prefscardAging) {
    this.prefscardAging = prefscardAging;
  }

  public Boards prefscardCovers(String prefscardCovers) {
    this.prefscardCovers = prefscardCovers;
    return this;
  }

   /**
   *  true or false
   * @return prefscardCovers
  **/
  @Schema(description = " true or false")
  public String getPrefscardCovers() {
    return prefscardCovers;
  }

  public void setPrefscardCovers(String prefscardCovers) {
    this.prefscardCovers = prefscardCovers;
  }

  public Boards prefscomments(String prefscomments) {
    this.prefscomments = prefscomments;
    return this;
  }

   /**
   * One of: disabled, members, observers, org or public
   * @return prefscomments
  **/
  @Schema(description = "One of: disabled, members, observers, org or public")
  public String getPrefscomments() {
    return prefscomments;
  }

  public void setPrefscomments(String prefscomments) {
    this.prefscomments = prefscomments;
  }

  public Boards prefsinvitations(String prefsinvitations) {
    this.prefsinvitations = prefsinvitations;
    return this;
  }

   /**
   * One of: admins or members
   * @return prefsinvitations
  **/
  @Schema(description = "One of: admins or members")
  public String getPrefsinvitations() {
    return prefsinvitations;
  }

  public void setPrefsinvitations(String prefsinvitations) {
    this.prefsinvitations = prefsinvitations;
  }

  public Boards prefspermissionLevel(String prefspermissionLevel) {
    this.prefspermissionLevel = prefspermissionLevel;
    return this;
  }

   /**
   * One of: org, private or public
   * @return prefspermissionLevel
  **/
  @Schema(description = "One of: org, private or public")
  public String getPrefspermissionLevel() {
    return prefspermissionLevel;
  }

  public void setPrefspermissionLevel(String prefspermissionLevel) {
    this.prefspermissionLevel = prefspermissionLevel;
  }

  public Boards prefsselfJoin(String prefsselfJoin) {
    this.prefsselfJoin = prefsselfJoin;
    return this;
  }

   /**
   *  true or false
   * @return prefsselfJoin
  **/
  @Schema(description = " true or false")
  public String getPrefsselfJoin() {
    return prefsselfJoin;
  }

  public void setPrefsselfJoin(String prefsselfJoin) {
    this.prefsselfJoin = prefsselfJoin;
  }

  public Boards prefsvoting(String prefsvoting) {
    this.prefsvoting = prefsvoting;
    return this;
  }

   /**
   * One of: disabled, members, observers, org or public
   * @return prefsvoting
  **/
  @Schema(description = "One of: disabled, members, observers, org or public")
  public String getPrefsvoting() {
    return prefsvoting;
  }

  public void setPrefsvoting(String prefsvoting) {
    this.prefsvoting = prefsvoting;
  }

  public Boards prefsBackground(String prefsBackground) {
    this.prefsBackground = prefsBackground;
    return this;
  }

   /**
   * a string with a length from 0 to 16384
   * @return prefsBackground
  **/
  @Schema(description = "a string with a length from 0 to 16384")
  public String getPrefsBackground() {
    return prefsBackground;
  }

  public void setPrefsBackground(String prefsBackground) {
    this.prefsBackground = prefsBackground;
  }

  public Boards prefsCardAging(String prefsCardAging) {
    this.prefsCardAging = prefsCardAging;
    return this;
  }

   /**
   * One of: pirate or regular
   * @return prefsCardAging
  **/
  @Schema(description = "One of: pirate or regular")
  public String getPrefsCardAging() {
    return prefsCardAging;
  }

  public void setPrefsCardAging(String prefsCardAging) {
    this.prefsCardAging = prefsCardAging;
  }

  public Boards prefsCardCovers(String prefsCardCovers) {
    this.prefsCardCovers = prefsCardCovers;
    return this;
  }

   /**
   *  true or false
   * @return prefsCardCovers
  **/
  @Schema(description = " true or false")
  public String getPrefsCardCovers() {
    return prefsCardCovers;
  }

  public void setPrefsCardCovers(String prefsCardCovers) {
    this.prefsCardCovers = prefsCardCovers;
  }

  public Boards prefsComments(String prefsComments) {
    this.prefsComments = prefsComments;
    return this;
  }

   /**
   * One of: disabled, members, observers, org or public
   * @return prefsComments
  **/
  @Schema(description = "One of: disabled, members, observers, org or public")
  public String getPrefsComments() {
    return prefsComments;
  }

  public void setPrefsComments(String prefsComments) {
    this.prefsComments = prefsComments;
  }

  public Boards prefsInvitations(String prefsInvitations) {
    this.prefsInvitations = prefsInvitations;
    return this;
  }

   /**
   * One of: admins or members
   * @return prefsInvitations
  **/
  @Schema(description = "One of: admins or members")
  public String getPrefsInvitations() {
    return prefsInvitations;
  }

  public void setPrefsInvitations(String prefsInvitations) {
    this.prefsInvitations = prefsInvitations;
  }

  public Boards prefsPermissionLevel(String prefsPermissionLevel) {
    this.prefsPermissionLevel = prefsPermissionLevel;
    return this;
  }

   /**
   * One of: org, private or public
   * @return prefsPermissionLevel
  **/
  @Schema(description = "One of: org, private or public")
  public String getPrefsPermissionLevel() {
    return prefsPermissionLevel;
  }

  public void setPrefsPermissionLevel(String prefsPermissionLevel) {
    this.prefsPermissionLevel = prefsPermissionLevel;
  }

  public Boards prefsSelfJoin(String prefsSelfJoin) {
    this.prefsSelfJoin = prefsSelfJoin;
    return this;
  }

   /**
   *  true or false
   * @return prefsSelfJoin
  **/
  @Schema(description = " true or false")
  public String getPrefsSelfJoin() {
    return prefsSelfJoin;
  }

  public void setPrefsSelfJoin(String prefsSelfJoin) {
    this.prefsSelfJoin = prefsSelfJoin;
  }

  public Boards prefsVoting(String prefsVoting) {
    this.prefsVoting = prefsVoting;
    return this;
  }

   /**
   * One of: disabled, members, observers, org or public
   * @return prefsVoting
  **/
  @Schema(description = "One of: disabled, members, observers, org or public")
  public String getPrefsVoting() {
    return prefsVoting;
  }

  public void setPrefsVoting(String prefsVoting) {
    this.prefsVoting = prefsVoting;
  }

  public Boards subscribed(String subscribed) {
    this.subscribed = subscribed;
    return this;
  }

   /**
   *  true or false
   * @return subscribed
  **/
  @Schema(description = " true or false")
  public String getSubscribed() {
    return subscribed;
  }

  public void setSubscribed(String subscribed) {
    this.subscribed = subscribed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Boards boards = (Boards) o;
    return Objects.equals(this.closed, boards.closed) &&
        Objects.equals(this.desc, boards.desc) &&
        Objects.equals(this.idBoardSource, boards.idBoardSource) &&
        Objects.equals(this.idOrganization, boards.idOrganization) &&
        Objects.equals(this.keepFromSource, boards.keepFromSource) &&
        Objects.equals(this.labelNamesblue, boards.labelNamesblue) &&
        Objects.equals(this.labelNamesgreen, boards.labelNamesgreen) &&
        Objects.equals(this.labelNamesorange, boards.labelNamesorange) &&
        Objects.equals(this.labelNamespurple, boards.labelNamespurple) &&
        Objects.equals(this.labelNamesred, boards.labelNamesred) &&
        Objects.equals(this.labelNamesyellow, boards.labelNamesyellow) &&
        Objects.equals(this.name, boards.name) &&
        Objects.equals(this.powerUps, boards.powerUps) &&
        Objects.equals(this.prefsbackground, boards.prefsbackground) &&
        Objects.equals(this.prefscalendarFeedEnabled, boards.prefscalendarFeedEnabled) &&
        Objects.equals(this.prefscardAging, boards.prefscardAging) &&
        Objects.equals(this.prefscardCovers, boards.prefscardCovers) &&
        Objects.equals(this.prefscomments, boards.prefscomments) &&
        Objects.equals(this.prefsinvitations, boards.prefsinvitations) &&
        Objects.equals(this.prefspermissionLevel, boards.prefspermissionLevel) &&
        Objects.equals(this.prefsselfJoin, boards.prefsselfJoin) &&
        Objects.equals(this.prefsvoting, boards.prefsvoting) &&
        Objects.equals(this.prefsBackground, boards.prefsBackground) &&
        Objects.equals(this.prefsCardAging, boards.prefsCardAging) &&
        Objects.equals(this.prefsCardCovers, boards.prefsCardCovers) &&
        Objects.equals(this.prefsComments, boards.prefsComments) &&
        Objects.equals(this.prefsInvitations, boards.prefsInvitations) &&
        Objects.equals(this.prefsPermissionLevel, boards.prefsPermissionLevel) &&
        Objects.equals(this.prefsSelfJoin, boards.prefsSelfJoin) &&
        Objects.equals(this.prefsVoting, boards.prefsVoting) &&
        Objects.equals(this.subscribed, boards.subscribed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(closed, desc, idBoardSource, idOrganization, keepFromSource, labelNamesblue, labelNamesgreen, labelNamesorange, labelNamespurple, labelNamesred, labelNamesyellow, name, powerUps, prefsbackground, prefscalendarFeedEnabled, prefscardAging, prefscardCovers, prefscomments, prefsinvitations, prefspermissionLevel, prefsselfJoin, prefsvoting, prefsBackground, prefsCardAging, prefsCardCovers, prefsComments, prefsInvitations, prefsPermissionLevel, prefsSelfJoin, prefsVoting, subscribed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Boards {\n");
    
    sb.append("    closed: ").append(toIndentedString(closed)).append("\n");
    sb.append("    desc: ").append(toIndentedString(desc)).append("\n");
    sb.append("    idBoardSource: ").append(toIndentedString(idBoardSource)).append("\n");
    sb.append("    idOrganization: ").append(toIndentedString(idOrganization)).append("\n");
    sb.append("    keepFromSource: ").append(toIndentedString(keepFromSource)).append("\n");
    sb.append("    labelNamesblue: ").append(toIndentedString(labelNamesblue)).append("\n");
    sb.append("    labelNamesgreen: ").append(toIndentedString(labelNamesgreen)).append("\n");
    sb.append("    labelNamesorange: ").append(toIndentedString(labelNamesorange)).append("\n");
    sb.append("    labelNamespurple: ").append(toIndentedString(labelNamespurple)).append("\n");
    sb.append("    labelNamesred: ").append(toIndentedString(labelNamesred)).append("\n");
    sb.append("    labelNamesyellow: ").append(toIndentedString(labelNamesyellow)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    powerUps: ").append(toIndentedString(powerUps)).append("\n");
    sb.append("    prefsbackground: ").append(toIndentedString(prefsbackground)).append("\n");
    sb.append("    prefscalendarFeedEnabled: ").append(toIndentedString(prefscalendarFeedEnabled)).append("\n");
    sb.append("    prefscardAging: ").append(toIndentedString(prefscardAging)).append("\n");
    sb.append("    prefscardCovers: ").append(toIndentedString(prefscardCovers)).append("\n");
    sb.append("    prefscomments: ").append(toIndentedString(prefscomments)).append("\n");
    sb.append("    prefsinvitations: ").append(toIndentedString(prefsinvitations)).append("\n");
    sb.append("    prefspermissionLevel: ").append(toIndentedString(prefspermissionLevel)).append("\n");
    sb.append("    prefsselfJoin: ").append(toIndentedString(prefsselfJoin)).append("\n");
    sb.append("    prefsvoting: ").append(toIndentedString(prefsvoting)).append("\n");
    sb.append("    prefsBackground: ").append(toIndentedString(prefsBackground)).append("\n");
    sb.append("    prefsCardAging: ").append(toIndentedString(prefsCardAging)).append("\n");
    sb.append("    prefsCardCovers: ").append(toIndentedString(prefsCardCovers)).append("\n");
    sb.append("    prefsComments: ").append(toIndentedString(prefsComments)).append("\n");
    sb.append("    prefsInvitations: ").append(toIndentedString(prefsInvitations)).append("\n");
    sb.append("    prefsPermissionLevel: ").append(toIndentedString(prefsPermissionLevel)).append("\n");
    sb.append("    prefsSelfJoin: ").append(toIndentedString(prefsSelfJoin)).append("\n");
    sb.append("    prefsVoting: ").append(toIndentedString(prefsVoting)).append("\n");
    sb.append("    subscribed: ").append(toIndentedString(subscribed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
