/*
 * Trello
 * This document describes the REST API of Trello as published by Trello.com.  - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>  - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CardsChecklistIdChecklistCurrentCheckItem
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-05-12T10:27:01.792+02:00[Europe/Berlin]")
public class CardsChecklistIdChecklistCurrentCheckItem {
  @SerializedName("idChecklist")
  private String idChecklist = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("pos")
  private String pos = null;

  @SerializedName("state")
  private String state = null;

  public CardsChecklistIdChecklistCurrentCheckItem idChecklist(String idChecklist) {
    this.idChecklist = idChecklist;
    return this;
  }

   /**
   * An id, or null
   * @return idChecklist
  **/
  @Schema(description = "An id, or null")
  public String getIdChecklist() {
    return idChecklist;
  }

  public void setIdChecklist(String idChecklist) {
    this.idChecklist = idChecklist;
  }

  public CardsChecklistIdChecklistCurrentCheckItem name(String name) {
    this.name = name;
    return this;
  }

   /**
   * a string with a length from 1 to 16384
   * @return name
  **/
  @Schema(description = "a string with a length from 1 to 16384")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CardsChecklistIdChecklistCurrentCheckItem pos(String pos) {
    this.pos = pos;
    return this;
  }

   /**
   * A position. top , bottom , or a positive number.
   * @return pos
  **/
  @Schema(description = "A position. top , bottom , or a positive number.")
  public String getPos() {
    return pos;
  }

  public void setPos(String pos) {
    this.pos = pos;
  }

  public CardsChecklistIdChecklistCurrentCheckItem state(String state) {
    this.state = state;
    return this;
  }

   /**
   * One of: complete, false, incomplete or true
   * @return state
  **/
  @Schema(description = "One of: complete, false, incomplete or true")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CardsChecklistIdChecklistCurrentCheckItem cardsChecklistIdChecklistCurrentCheckItem = (CardsChecklistIdChecklistCurrentCheckItem) o;
    return Objects.equals(this.idChecklist, cardsChecklistIdChecklistCurrentCheckItem.idChecklist) &&
        Objects.equals(this.name, cardsChecklistIdChecklistCurrentCheckItem.name) &&
        Objects.equals(this.pos, cardsChecklistIdChecklistCurrentCheckItem.pos) &&
        Objects.equals(this.state, cardsChecklistIdChecklistCurrentCheckItem.state);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idChecklist, name, pos, state);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CardsChecklistIdChecklistCurrentCheckItem {\n");
    
    sb.append("    idChecklist: ").append(toIndentedString(idChecklist)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    pos: ").append(toIndentedString(pos)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
