/*
 * Trello
 * This document describes the REST API of Trello as published by Trello.com.  - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>  - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CardsIdBoard
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-05-12T10:27:01.792+02:00[Europe/Berlin]")
public class CardsIdBoard {
  @SerializedName("idList")
  private String idList = null;

  @SerializedName("value")
  private String value = null;

  public CardsIdBoard idList(String idList) {
    this.idList = idList;
    return this;
  }

   /**
   * id of the list that the card should be moved to on the new board
   * @return idList
  **/
  @Schema(description = "id of the list that the card should be moved to on the new board")
  public String getIdList() {
    return idList;
  }

  public void setIdList(String idList) {
    this.idList = idList;
  }

  public CardsIdBoard value(String value) {
    this.value = value;
    return this;
  }

   /**
   * id of the board the card should be moved to
   * @return value
  **/
  @Schema(description = "id of the board the card should be moved to")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CardsIdBoard cardsIdBoard = (CardsIdBoard) o;
    return Objects.equals(this.idList, cardsIdBoard.idList) &&
        Objects.equals(this.value, cardsIdBoard.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idList, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CardsIdBoard {\n");
    
    sb.append("    idList: ").append(toIndentedString(idList)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
