/*
 * Trello
 * This document describes the REST API of Trello as published by Trello.com.  - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>  - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CardsAttachments
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-05-12T10:27:01.792+02:00[Europe/Berlin]")
public class CardsAttachments {
  @SerializedName("file")
  private String file = null;

  @SerializedName("mimeType")
  private String mimeType = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("url")
  private String url = null;

  public CardsAttachments file(String file) {
    this.file = file;
    return this;
  }

   /**
   * A file
   * @return file
  **/
  @Schema(description = "A file")
  public String getFile() {
    return file;
  }

  public void setFile(String file) {
    this.file = file;
  }

  public CardsAttachments mimeType(String mimeType) {
    this.mimeType = mimeType;
    return this;
  }

   /**
   * a string with a length from 0 to 256
   * @return mimeType
  **/
  @Schema(description = "a string with a length from 0 to 256")
  public String getMimeType() {
    return mimeType;
  }

  public void setMimeType(String mimeType) {
    this.mimeType = mimeType;
  }

  public CardsAttachments name(String name) {
    this.name = name;
    return this;
  }

   /**
   * a string with a length from 0 to 256
   * @return name
  **/
  @Schema(description = "a string with a length from 0 to 256")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CardsAttachments url(String url) {
    this.url = url;
    return this;
  }

   /**
   * A URL starting with http:// or https:// or null
   * @return url
  **/
  @Schema(description = "A URL starting with http:// or https:// or null")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CardsAttachments cardsAttachments = (CardsAttachments) o;
    return Objects.equals(this.file, cardsAttachments.file) &&
        Objects.equals(this.mimeType, cardsAttachments.mimeType) &&
        Objects.equals(this.name, cardsAttachments.name) &&
        Objects.equals(this.url, cardsAttachments.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(file, mimeType, name, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CardsAttachments {\n");
    
    sb.append("    file: ").append(toIndentedString(file)).append("\n");
    sb.append("    mimeType: ").append(toIndentedString(mimeType)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
