/*
 * Trello
 * This document describes the REST API of Trello as published by Trello.com.  - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>  - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CardsChecklists
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-05-12T10:27:01.792+02:00[Europe/Berlin]")
public class CardsChecklists {
  @SerializedName("idChecklistSource")
  private String idChecklistSource = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("value")
  private String value = null;

  public CardsChecklists idChecklistSource(String idChecklistSource) {
    this.idChecklistSource = idChecklistSource;
    return this;
  }

   /**
   * The id of the source checklist to copy into a new checklist.
   * @return idChecklistSource
  **/
  @Schema(description = "The id of the source checklist to copy into a new checklist.")
  public String getIdChecklistSource() {
    return idChecklistSource;
  }

  public void setIdChecklistSource(String idChecklistSource) {
    this.idChecklistSource = idChecklistSource;
  }

  public CardsChecklists name(String name) {
    this.name = name;
    return this;
  }

   /**
   * a string with a length from 0 to 16384
   * @return name
  **/
  @Schema(description = "a string with a length from 0 to 16384")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CardsChecklists value(String value) {
    this.value = value;
    return this;
  }

   /**
   * The id of the checklist to add to the card, or null to create a new one.
   * @return value
  **/
  @Schema(description = "The id of the checklist to add to the card, or null to create a new one.")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CardsChecklists cardsChecklists = (CardsChecklists) o;
    return Objects.equals(this.idChecklistSource, cardsChecklists.idChecklistSource) &&
        Objects.equals(this.name, cardsChecklists.name) &&
        Objects.equals(this.value, cardsChecklists.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idChecklistSource, name, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CardsChecklists {\n");
    
    sb.append("    idChecklistSource: ").append(toIndentedString(idChecklistSource)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
