/*
 * Trello
 * This document describes the REST API of Trello as published by Trello.com.  - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>  - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ListsCards
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-05-12T10:27:01.792+02:00[Europe/Berlin]")
public class ListsCards {
  @SerializedName("desc")
  private String desc = null;

  @SerializedName("due")
  private String due = null;

  @SerializedName("idMembers")
  private String idMembers = null;

  @SerializedName("labels")
  private String labels = null;

  @SerializedName("name")
  private String name = null;

  public ListsCards desc(String desc) {
    this.desc = desc;
    return this;
  }

   /**
   * a string with a length from 0 to 16384
   * @return desc
  **/
  @Schema(description = "a string with a length from 0 to 16384")
  public String getDesc() {
    return desc;
  }

  public void setDesc(String desc) {
    this.desc = desc;
  }

  public ListsCards due(String due) {
    this.due = due;
    return this;
  }

   /**
   * A date, or null
   * @return due
  **/
  @Schema(description = "A date, or null")
  public String getDue() {
    return due;
  }

  public void setDue(String due) {
    this.due = due;
  }

  public ListsCards idMembers(String idMembers) {
    this.idMembers = idMembers;
    return this;
  }

   /**
   * A comma-separated list of objectIds, 24-character hex strings
   * @return idMembers
  **/
  @Schema(description = "A comma-separated list of objectIds, 24-character hex strings")
  public String getIdMembers() {
    return idMembers;
  }

  public void setIdMembers(String idMembers) {
    this.idMembers = idMembers;
  }

  public ListsCards labels(String labels) {
    this.labels = labels;
    return this;
  }

   /**
   * all or a comma-separated list of: blue, green, orange, purple, red or yellow
   * @return labels
  **/
  @Schema(description = "all or a comma-separated list of: blue, green, orange, purple, red or yellow")
  public String getLabels() {
    return labels;
  }

  public void setLabels(String labels) {
    this.labels = labels;
  }

  public ListsCards name(String name) {
    this.name = name;
    return this;
  }

   /**
   * a string with a length from 1 to 16384
   * @return name
  **/
  @Schema(description = "a string with a length from 1 to 16384")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListsCards listsCards = (ListsCards) o;
    return Objects.equals(this.desc, listsCards.desc) &&
        Objects.equals(this.due, listsCards.due) &&
        Objects.equals(this.idMembers, listsCards.idMembers) &&
        Objects.equals(this.labels, listsCards.labels) &&
        Objects.equals(this.name, listsCards.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(desc, due, idMembers, labels, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListsCards {\n");
    
    sb.append("    desc: ").append(toIndentedString(desc)).append("\n");
    sb.append("    due: ").append(toIndentedString(due)).append("\n");
    sb.append("    idMembers: ").append(toIndentedString(idMembers)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
