/*
 * Trello
 * This document describes the REST API of Trello as published by Trello.com.  - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>  - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Lists
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-05-12T10:27:01.792+02:00[Europe/Berlin]")
public class Lists {
  @SerializedName("closed")
  private String closed = null;

  @SerializedName("idBoard")
  private String idBoard = null;

  @SerializedName("idListSource")
  private String idListSource = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("pos")
  private String pos = null;

  @SerializedName("subscribed")
  private String subscribed = null;

  public Lists closed(String closed) {
    this.closed = closed;
    return this;
  }

   /**
   *  true or false
   * @return closed
  **/
  @Schema(description = " true or false")
  public String getClosed() {
    return closed;
  }

  public void setClosed(String closed) {
    this.closed = closed;
  }

  public Lists idBoard(String idBoard) {
    this.idBoard = idBoard;
    return this;
  }

   /**
   * id of the board that the list should be added to
   * @return idBoard
  **/
  @Schema(description = "id of the board that the list should be added to")
  public String getIdBoard() {
    return idBoard;
  }

  public void setIdBoard(String idBoard) {
    this.idBoard = idBoard;
  }

  public Lists idListSource(String idListSource) {
    this.idListSource = idListSource;
    return this;
  }

   /**
   * The id of the list to copy into a new list.
   * @return idListSource
  **/
  @Schema(description = "The id of the list to copy into a new list.")
  public String getIdListSource() {
    return idListSource;
  }

  public void setIdListSource(String idListSource) {
    this.idListSource = idListSource;
  }

  public Lists name(String name) {
    this.name = name;
    return this;
  }

   /**
   * a string with a length from 1 to 16384
   * @return name
  **/
  @Schema(description = "a string with a length from 1 to 16384")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Lists pos(String pos) {
    this.pos = pos;
    return this;
  }

   /**
   * A position. top , bottom , or a positive number.
   * @return pos
  **/
  @Schema(description = "A position. top , bottom , or a positive number.")
  public String getPos() {
    return pos;
  }

  public void setPos(String pos) {
    this.pos = pos;
  }

  public Lists subscribed(String subscribed) {
    this.subscribed = subscribed;
    return this;
  }

   /**
   *  true or false
   * @return subscribed
  **/
  @Schema(description = " true or false")
  public String getSubscribed() {
    return subscribed;
  }

  public void setSubscribed(String subscribed) {
    this.subscribed = subscribed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Lists lists = (Lists) o;
    return Objects.equals(this.closed, lists.closed) &&
        Objects.equals(this.idBoard, lists.idBoard) &&
        Objects.equals(this.idListSource, lists.idListSource) &&
        Objects.equals(this.name, lists.name) &&
        Objects.equals(this.pos, lists.pos) &&
        Objects.equals(this.subscribed, lists.subscribed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(closed, idBoard, idListSource, name, pos, subscribed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Lists {\n");
    
    sb.append("    closed: ").append(toIndentedString(closed)).append("\n");
    sb.append("    idBoard: ").append(toIndentedString(idBoard)).append("\n");
    sb.append("    idListSource: ").append(toIndentedString(idListSource)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    pos: ").append(toIndentedString(pos)).append("\n");
    sb.append("    subscribed: ").append(toIndentedString(subscribed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
