/*
 * Trello
 * This document describes the REST API of Trello as published by Trello.com.  - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>  - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Members
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-05-12T10:27:01.792+02:00[Europe/Berlin]")
public class Members {
  @SerializedName("avatarSource")
  private String avatarSource = null;

  @SerializedName("bio")
  private String bio = null;

  @SerializedName("fullName")
  private String fullName = null;

  @SerializedName("initials")
  private String initials = null;

  @SerializedName("prefs/colorBlind")
  private String prefscolorBlind = null;

  @SerializedName("prefs/locale")
  private String prefslocale = null;

  @SerializedName("prefs/minutesBetweenSummaries")
  private String prefsminutesBetweenSummaries = null;

  @SerializedName("username")
  private String username = null;

  public Members avatarSource(String avatarSource) {
    this.avatarSource = avatarSource;
    return this;
  }

   /**
   * One of: gravatar, none or upload
   * @return avatarSource
  **/
  @Schema(description = "One of: gravatar, none or upload")
  public String getAvatarSource() {
    return avatarSource;
  }

  public void setAvatarSource(String avatarSource) {
    this.avatarSource = avatarSource;
  }

  public Members bio(String bio) {
    this.bio = bio;
    return this;
  }

   /**
   * a string with a length from 0 to 16384
   * @return bio
  **/
  @Schema(description = "a string with a length from 0 to 16384")
  public String getBio() {
    return bio;
  }

  public void setBio(String bio) {
    this.bio = bio;
  }

  public Members fullName(String fullName) {
    this.fullName = fullName;
    return this;
  }

   /**
   * A string with a length of at least 1.  Cannot begin or end with a space.
   * @return fullName
  **/
  @Schema(description = "A string with a length of at least 1.  Cannot begin or end with a space.")
  public String getFullName() {
    return fullName;
  }

  public void setFullName(String fullName) {
    this.fullName = fullName;
  }

  public Members initials(String initials) {
    this.initials = initials;
    return this;
  }

   /**
   * A string with a length from 1 to 4.  Cannot begin or end with a space
   * @return initials
  **/
  @Schema(description = "A string with a length from 1 to 4.  Cannot begin or end with a space")
  public String getInitials() {
    return initials;
  }

  public void setInitials(String initials) {
    this.initials = initials;
  }

  public Members prefscolorBlind(String prefscolorBlind) {
    this.prefscolorBlind = prefscolorBlind;
    return this;
  }

   /**
   *  true or false
   * @return prefscolorBlind
  **/
  @Schema(description = " true or false")
  public String getPrefscolorBlind() {
    return prefscolorBlind;
  }

  public void setPrefscolorBlind(String prefscolorBlind) {
    this.prefscolorBlind = prefscolorBlind;
  }

  public Members prefslocale(String prefslocale) {
    this.prefslocale = prefslocale;
    return this;
  }

   /**
   * a string with a length from 0 to 255
   * @return prefslocale
  **/
  @Schema(description = "a string with a length from 0 to 255")
  public String getPrefslocale() {
    return prefslocale;
  }

  public void setPrefslocale(String prefslocale) {
    this.prefslocale = prefslocale;
  }

  public Members prefsminutesBetweenSummaries(String prefsminutesBetweenSummaries) {
    this.prefsminutesBetweenSummaries = prefsminutesBetweenSummaries;
    return this;
  }

   /**
   * -1 (disabled), 1 or 60
   * @return prefsminutesBetweenSummaries
  **/
  @Schema(description = "-1 (disabled), 1 or 60")
  public String getPrefsminutesBetweenSummaries() {
    return prefsminutesBetweenSummaries;
  }

  public void setPrefsminutesBetweenSummaries(String prefsminutesBetweenSummaries) {
    this.prefsminutesBetweenSummaries = prefsminutesBetweenSummaries;
  }

  public Members username(String username) {
    this.username = username;
    return this;
  }

   /**
   * A string with a length of at least 3.  Only lowercase letters, underscores, and numbers are allowed.  Must be unique.
   * @return username
  **/
  @Schema(description = "A string with a length of at least 3.  Only lowercase letters, underscores, and numbers are allowed.  Must be unique.")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Members members = (Members) o;
    return Objects.equals(this.avatarSource, members.avatarSource) &&
        Objects.equals(this.bio, members.bio) &&
        Objects.equals(this.fullName, members.fullName) &&
        Objects.equals(this.initials, members.initials) &&
        Objects.equals(this.prefscolorBlind, members.prefscolorBlind) &&
        Objects.equals(this.prefslocale, members.prefslocale) &&
        Objects.equals(this.prefsminutesBetweenSummaries, members.prefsminutesBetweenSummaries) &&
        Objects.equals(this.username, members.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(avatarSource, bio, fullName, initials, prefscolorBlind, prefslocale, prefsminutesBetweenSummaries, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Members {\n");
    
    sb.append("    avatarSource: ").append(toIndentedString(avatarSource)).append("\n");
    sb.append("    bio: ").append(toIndentedString(bio)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    initials: ").append(toIndentedString(initials)).append("\n");
    sb.append("    prefscolorBlind: ").append(toIndentedString(prefscolorBlind)).append("\n");
    sb.append("    prefslocale: ").append(toIndentedString(prefslocale)).append("\n");
    sb.append("    prefsminutesBetweenSummaries: ").append(toIndentedString(prefsminutesBetweenSummaries)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
