/*
 * Trello
 * This document describes the REST API of Trello as published by Trello.com.  - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>  - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * MembersBoardBackgrounds
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-05-12T10:27:01.792+02:00[Europe/Berlin]")
public class MembersBoardBackgrounds {
  @SerializedName("brightness")
  private String brightness = null;

  @SerializedName("file")
  private String file = null;

  @SerializedName("tile")
  private String tile = null;

  public MembersBoardBackgrounds brightness(String brightness) {
    this.brightness = brightness;
    return this;
  }

   /**
   * One of: dark, light or unknown
   * @return brightness
  **/
  @Schema(description = "One of: dark, light or unknown")
  public String getBrightness() {
    return brightness;
  }

  public void setBrightness(String brightness) {
    this.brightness = brightness;
  }

  public MembersBoardBackgrounds file(String file) {
    this.file = file;
    return this;
  }

   /**
   * A file
   * @return file
  **/
  @Schema(description = "A file")
  public String getFile() {
    return file;
  }

  public void setFile(String file) {
    this.file = file;
  }

  public MembersBoardBackgrounds tile(String tile) {
    this.tile = tile;
    return this;
  }

   /**
   *  true or false
   * @return tile
  **/
  @Schema(description = " true or false")
  public String getTile() {
    return tile;
  }

  public void setTile(String tile) {
    this.tile = tile;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MembersBoardBackgrounds membersBoardBackgrounds = (MembersBoardBackgrounds) o;
    return Objects.equals(this.brightness, membersBoardBackgrounds.brightness) &&
        Objects.equals(this.file, membersBoardBackgrounds.file) &&
        Objects.equals(this.tile, membersBoardBackgrounds.tile);
  }

  @Override
  public int hashCode() {
    return Objects.hash(brightness, file, tile);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MembersBoardBackgrounds {\n");
    
    sb.append("    brightness: ").append(toIndentedString(brightness)).append("\n");
    sb.append("    file: ").append(toIndentedString(file)).append("\n");
    sb.append("    tile: ").append(toIndentedString(tile)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
