/*
 * Trello
 * This document describes the REST API of Trello as published by Trello.com.  - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>  - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Sessions
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-05-12T10:27:01.792+02:00[Europe/Berlin]")
public class Sessions {
  @SerializedName("idBoard")
  private String idBoard = null;

  @SerializedName("status")
  private String status = null;

  public Sessions idBoard(String idBoard) {
    this.idBoard = idBoard;
    return this;
  }

   /**
   * The id of the board you&amp;#39;re viewing.  Boards with no viewers will not get updates about members&amp;#39; statuses.
   * @return idBoard
  **/
  @Schema(description = "The id of the board you&#39;re viewing.  Boards with no viewers will not get updates about members&#39; statuses.")
  public String getIdBoard() {
    return idBoard;
  }

  public void setIdBoard(String idBoard) {
    this.idBoard = idBoard;
  }

  public Sessions status(String status) {
    this.status = status;
    return this;
  }

   /**
   * One of: active, disconnected or idle
   * @return status
  **/
  @Schema(description = "One of: active, disconnected or idle")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Sessions sessions = (Sessions) o;
    return Objects.equals(this.idBoard, sessions.idBoard) &&
        Objects.equals(this.status, sessions.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idBoard, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Sessions {\n");
    
    sb.append("    idBoard: ").append(toIndentedString(idBoard)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
