/*
 * Trello
 * This document describes the REST API of Trello as published by Trello.com.  - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>  - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * TokensWebhooks
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-05-12T10:27:01.792+02:00[Europe/Berlin]")
public class TokensWebhooks {
  @SerializedName("callbackURL")
  private String callbackURL = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("idModel")
  private String idModel = null;

  public TokensWebhooks callbackURL(String callbackURL) {
    this.callbackURL = callbackURL;
    return this;
  }

   /**
   * A valid URL that is reachable with a HEAD request
   * @return callbackURL
  **/
  @Schema(description = "A valid URL that is reachable with a HEAD request")
  public String getCallbackURL() {
    return callbackURL;
  }

  public void setCallbackURL(String callbackURL) {
    this.callbackURL = callbackURL;
  }

  public TokensWebhooks description(String description) {
    this.description = description;
    return this;
  }

   /**
   * a string with a length from 0 to 16384
   * @return description
  **/
  @Schema(description = "a string with a length from 0 to 16384")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public TokensWebhooks idModel(String idModel) {
    this.idModel = idModel;
    return this;
  }

   /**
   * id of the model to be monitored
   * @return idModel
  **/
  @Schema(description = "id of the model to be monitored")
  public String getIdModel() {
    return idModel;
  }

  public void setIdModel(String idModel) {
    this.idModel = idModel;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TokensWebhooks tokensWebhooks = (TokensWebhooks) o;
    return Objects.equals(this.callbackURL, tokensWebhooks.callbackURL) &&
        Objects.equals(this.description, tokensWebhooks.description) &&
        Objects.equals(this.idModel, tokensWebhooks.idModel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(callbackURL, description, idModel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TokensWebhooks {\n");
    
    sb.append("    callbackURL: ").append(toIndentedString(callbackURL)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    idModel: ").append(toIndentedString(idModel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
